### ISSUE TITLE
Implement mrbayes_volpiano phylogenetics interface

### ISSUE THREAD

**Issue by hajicj** [Genome-of-Melody/chantlab_frontend#12]
This has multiple aspects:

- The phylogenetic tree needs to be displayed. Probably its own display page on the same level as the alignment display. Should leverage existing tools for displaying phylo trees as much as possible. "Lightweight solution" is to only compute the tree and spit out the newick file for the summary tree, and then let the user upload it for visualization into a different site.
- Needs to be integrated into the website workflows. Input is an alignment, output is a tree. Trees need to be exportable, saveable, loadable, and uploadable. 
- We need to make it possible to construct multi-locus alignments (multiple Cantus IDs).

**Comment by lanzv** [comment]
Related to issues [Establish Backend Communication for MrBayes Volpiano Integration](https://github.com/Genome-of-Melody/chantlab_frontend/issues/20), [(Adapt Phylogeny Page Design to Match Alignment Page Layout](https://github.com/Genome-of-Melody/chantlab_frontend/issues/21), [Create Concatenated Alignment Page](https://github.com/Genome-of-Melody/chantlab_frontend/issues/22)
