### ISSUE TITLE
Normalize sigla for mrbayes_volpiano call

### ISSUE THREAD

**Issue by hajicj** [Genome-of-Melody/chantlab_frontend#25]
Normalize the sigla used in the mrbayes_volpiano call to ensure MrBayes Volpiano successful run.

**Comment by lanzv** [comment]
Solved on the backend
[Sigla standardization doesn't handle asterisk. #13](https://github.com/Genome-of-Melody/chantlab_backend/issues/13)
[Renaming nodes in guide/phylogenetic trees](https://github.com/Genome-of-Melody/chantlab_backend/issues/17)
