### ISSUE TITLE
Option to sort chant list by how many sources a Cantus ID appears in

### ISSUE THREAD

**Issue by hajicj** [Genome-of-Melody/chantlab_frontend#29]
This would make it much easier to experiment with phylogeny building using sensible data in the concatenated mode.

**Comment by lanzv** [comment]
Implemented here: [support sorting by cantus id frequencies + resolve undefined conservation numbers](https://github.com/Genome-of-Melody/chantlab_frontend/commit/4a36a72efb03ba5cdfcda1a6051d3b0c514a9314)
